### ISSUE TITLE
User privacy

### ISSUE THREAD

**Issue by LaurensDL** [superdav42/wp-multisite-waas#3]
When a user creates an account and log in on their dashboard, they can see other customers accounts on the users page, een if all settings in wp multisite waas are set to not create a account on the networks main site. This users page also shows the emailaddress which is a privacy concern.

<img width="457" alt="Problem users info" src="https://github.com/user-attachments/assets/e4aa1064-30a1-4bcc-b002-825b1bf56596" />

**Comment by superdav42** [comment]
I just tested it and it seems to be working properly for me. When a customer registers a site and logs into their own site they only see themselves and any users they add to that site. No other users are shown. Customers cannot login to the dashboard of the main site only their own site. 

In this case who are you logged in as and which site is being used to display the page? What role does the logged in account have?

**Comment by LaurensDL** [comment]
i just act as a client, create a site on the free plan and follow the normal flow for clients, all this on a incognito browser. The user can not see admins or something, but once another "normal flow user" creates a site, this new user also see the other users details and the first user now sees the new users details. you can try the flow and see what i mean yourself if u want @ https://biltsite.com/registration. Just choose the free plan, pick any template, visit the admin panel and click twice on users menu item to visit the users page.

**Comment by LaurensDL** [comment]
Issue fixed! Wasn't related to WP Multisite WaaS but rather Awedesk.
